### ISSUE TITLE
Fails on name.name with class cast exception for locale en-GB

### ISSUE THREAD

**Issue by andrewmccall** [andrewmccall/scala-faker#5]
```
scala> val c = new Config(locale="en-GB")
c: com.andrewmccall.faker.Config = com.andrewmccall.faker.Config@74a47783

scala> val faker = new Faker(c)
[INFO ] 2019-06-19 16:37:49.155 [run-main-3] ScalaModule$ - Loading Modules.
faker: com.andrewmccall.faker.Faker = com.andrewmccall.faker.Faker@47de5796

scala> faker("#{name.name}")
[INFO ] 2019-06-19 16:38:12.359 [run-main-3] Faker - Parsing #{name.name} with parent null
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class scala.collection.immutable.Map (java.util.ArrayList is in module java.base of loader 'bootstrap'; scala.collection.immutable.Map is in unnamed module of loader xsbt.boot.LibraryClassLoader @8e24743)
  at com.andrewmccall.faker.yaml.YamlData.containKeys(YamlData.scala:36)
  at com.andrewmccall.faker.yaml.YamlData.contains(YamlData.scala:25)
  at com.andrewmccall.faker.Faker.$anonfun$parse$1(Faker.scala:68)
  at scala.util.matching.Regex.$anonfun$replaceAllIn$1(Regex.scala:504)
  at scala.collection.Iterator.foreach(Iterator.scala:937)
  at scala.collection.Iterator.foreach$(Iterator.scala:937)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
  at scala.util.matching.Regex.replaceAllIn(Regex.scala:504)
  at com.andrewmccall.faker.Faker.parse(Faker.scala:50)
  at com.andrewmccall.faker.Faker.apply(Faker.scala:21)
  ... 36 elided
```

**Comment by andrewmccall** [comment]
This has been fixed.

**Comment by andrewmccall** [comment]
This isn't fixed.
